### ISSUE TITLE
Add support for eof

### ISSUE THREAD

**Issue by stoivo** [sublime-maude/maude_syntax_highlight#14]

**Comment by stoivo** [comment]
```
  data-section:
    - match: ^__END__\n
      scope: meta.string.ruby string.unquoted.program-block.ruby
      push:
        - meta_content_scope: text.plain
        - match: (?=<?xml|<(?i:html\b)|!DOCTYPE (?i:html\b))
          push:
            - meta_scope: text.html.embedded.ruby
            - include: scope:text.html.basic
```
