### ISSUE TITLE
Adding `op` and `ops` to syntax definition

### ISSUE THREAD

**Issue by ngraymon** [sublime-maude/maude_syntax_highlight#7]
Here are the pictures I wanted to share:

![SumatraPDF_lb1Du6FGkI](https://user-images.githubusercontent.com/4378720/159135184-6c1e0c9c-4ced-400a-bb53-f4f6e326bdbd.png)

![SumatraPDF_3PL7iRzYak](https://user-images.githubusercontent.com/4378720/159135189-0565d337-0b0a-4f16-98b8-48587a7907f9.png)
lets ignore **and then** for the moment and try to add it later

![sublime_text_wn8MHQzXEO](https://user-images.githubusercontent.com/4378720/159135171-3db8de6c-1ed4-4112-90cd-0b89a997c2fb.png)

**Comment by ngraymon** [comment]
![image](https://user-images.githubusercontent.com/4378720/159135215-bb252dad-8fe9-4d7f-9cd0-178f33834bc9.png)
I think its best to assume that parenthesis are not part of the syntax for the moment.

**Comment by ngraymon** [comment]
Found python syntax here:
https://github.com/sublimehq/Packages/blob/master/Python/Python.sublime-syntax
```yaml

  functions:
    - match: '^\s*(?:(async)\s+)?(def)\b'
      captures:
        1: keyword.declaration.async.python
        2: keyword.declaration.function.python
      push:
        - meta_scope: meta.function.python
        - include: line-continuation-or-pop
        - match: ':'
          scope: punctuation.section.function.begin.python
          pop: true
        - match: "(?={{identifier}})"
          push:
            - meta_content_scope: entity.name.function.python
            - include: entity-name-function
            - match: ''
              pop: true
        - match: '(?=\()'
          set:
            - match: \(
              scope: meta.function.parameters.python punctuation.section.parameters.begin.python
              set: [function-parameters, allow-unpack-operators]

  function-parameters:
    - meta_content_scope: meta.function.parameters.python
    - match: \)
      scope: punctuation.section.parameters.end.python
      set: function-after-parameters
    - include: comments
    - match: ','
      scope: punctuation.separator.parameters.python
      push: allow-unpack-operators
    - match: /
      scope: storage.modifier.positional-args-only.python
      push:
        - match: (?=[,)])
          pop: true
        - match: \S
          scope: invalid.illegal.expected-comma.python
    - match: '(?==)'
      set:
        - match: '='
          scope: keyword.operator.assignment.python
          set:
            - meta_scope: meta.function.parameters.default-value.python
            - match: '(?=[,)])'
              set: [function-parameters, allow-unpack-operators]
            - include: illegal-assignment-expression
            - include: expression-in-a-group
    - match: '(?=:)'
      set:
        - match: ':'
          scope: punctuation.separator.annotation.parameter.python
          set:
            - meta_scope: meta.function.parameters.annotation.python
            - match: '(?=[,)=])'
              set: function-parameters
            - include: illegal-assignment-expression
            - include: expression-in-a-group
    - include: function-parameters-tuple
    - include: illegal-names
    - match: '{{identifier}}'
      scope: variable.parameter.python
    - include: line-continuation

  function-parameters-tuple:
    # python 2 style tuple arguments
    # removed from python 3 since PEP-3113
    - match: \(
      scope: punctuation.section.group.begin.python
      push:
        - meta_scope: meta.group.python
        - match: \)
          scope: punctuation.section.group.end.python
          set: after-expression
        - include: comments
        - match: ','
          scope: punctuation.separator.parameters.python
          push: allow-unpack-operators
        # default values should follow the argument
        - match: '='
          push:
            - meta_scope: invalid.illegal.default-value.python
            - match: '(?=[,)=])'
              pop: true
        # python 2 does not support type annotations
        - match: '(?=:)'
          push:
            - meta_scope: invalid.illegal.annotation.python
            - match: '(?=[,)=])'
              pop: true
        - include: illegal-names
        - match: '{{identifier}}'
          scope: variable.parameter.python
        - include: line-continuation

  function-after-parameters:
    - meta_content_scope: meta.function.python
    - match: (?=->)
      set: [function-return-type, function-return-type-separator]
    - include: function-terminator

  function-return-type:
    - meta_content_scope: meta.function.annotation.return.python
    - include: illegal-assignment-expression
    - include: function-terminator
    - include: expression-in-a-statement

  function-return-type-separator:
    - match: ->
      scope: punctuation.separator.annotation.return.python
      pop: true

  function-terminator:
    - match: ':'
      scope: meta.function.python punctuation.section.function.begin.python
      pop: true
    - include: line-continuation-or-pop

```

**Comment by ngraymon** [comment]
You can use this
`set: [function-parameters, allow-unpack-operators]`

**Comment by ngraymon** [comment]
![SumatraPDF_lkRW9bjMEY](https://user-images.githubusercontent.com/4378720/159136268-82422ede-f31c-4dec-91b5-6b93f1bfd0c1.png)

**Comment by ngraymon** [comment]
![SumatraPDF_Au1NXPMkeb](https://user-images.githubusercontent.com/4378720/159136338-befb5530-0384-4c23-9c4e-18b86b932d6c.png)

**Comment by ngraymon** [comment]
![SumatraPDF_kdgJE4WZLK](https://user-images.githubusercontent.com/4378720/159136343-dfc8682c-ebd3-4819-9792-38c25c440217.png)

**Comment by ngraymon** [comment]
![SumatraPDF_1259khLjoe](https://user-images.githubusercontent.com/4378720/159136412-e8a1efb7-3097-483f-9ee7-211aab6942df.png)

**Comment by ngraymon** [comment]
41 / 615
![SumatraPDF_4R7veTD8iL](https://user-images.githubusercontent.com/4378720/159136559-5595b5df-c550-4ff9-be0a-de386a1a56b0.png)

**Comment by ngraymon** [comment]
The manual
http://maude.cs.illinois.edu/w/index.php/Maude_Manual_and_Examples

**Comment by ngraymon** [comment]
![firefox_PWEDRog7gs](https://user-images.githubusercontent.com/4378720/159136822-58cdcd14-b173-4d10-acd7-7e173906f1f5.png)

**Comment by ngraymon** [comment]
Probably it would be best to use a similar definition for 'simple identifiers' to avoid having to use the same regex everywhere. This seems like a factorization process that can be applied after the long version is implemented.

**Comment by stoivo** [comment]
After the brake I figured outsomething else which also stands in the docs.  The difference between push and set in 
```yml
  operators_signature:
    - match: \[
      scope: punctuation.operation.lable.start
      push:
        - match: ' '
        - match: ctor
          scope: keyword.control.ctor.maude
        - match: assoc
          scope: keyword.control.assoc.maude
        - match: comm
          scope: keyword.control.comm.maude
        - match: (left |right )?id
          scope: keyword.control.idendtity.maude
          push:
            - match: ": "
            - match: ([A-Za-z0-9-_!&^@#=$%*'+~/\\|?<>:;]*)
              pop: true
        - match: \]
          scope: punctuation.operation.lable.end
          pop: true
        - match: .
          scope: invalid.illegal
    - match: \.
      scope: keyword.operator.maude punctuation.operation.end
      pop: true
    - match: \S+
      scope: variable.parameter.maude.what
```
```yaml
  operators_signature:
    - match: \[
      scope: punctuation.operation.lable.start
      push:
        - match: ' '
        - match: ctor
          scope: keyword.control.ctor.maude
        - match: assoc
          scope: keyword.control.assoc.maude
        - match: comm
          scope: keyword.control.comm.maude
        - match: (left |right )?id
          scope: keyword.control.idendtity.maude
          set:
            - match: ": "
            - match: ([A-Za-z0-9-_!&^@#=$%*'+~/\\|?<>:;]*)
              pop: true
        - match: \]
          scope: punctuation.operation.lable.end
          pop: true
        - match: .
          scope: invalid.illegal
    - match: \.
      scope: keyword.operator.maude punctuation.operation.end
      pop: true
    - match: \S+
      scope: variable.parameter.maude.what
```

Set will replace the current will replace the current context but push will stack
![Screenshot 2022-03-19 at 23 07 17](https://user-images.githubusercontent.com/3492040/159140064-239b33a2-4130-478a-a71c-59ccdf3bff21.png)

**Comment by stoivo** [comment]
Here are our changes including some of my tests https://github.com/sublime-maude/maude_syntax_highlight/pull/9

**Comment by ngraymon** [comment]
So then we could use 'set' to have an 'identifier' scope for something like
'left id: rk5'
Where the 'rk5 would be 'identifier' scope and the 'left id:' would be the previous scope?

**Comment by stoivo** [comment]
No, when we do push we create a new context/ stackentry. Or so I think.

```yaml
operators_signature:
    - match: \[
      scope: punctuation.operation.lable.start
      push:
```
